id: 432
name: configSettingsRowTR
description: 'Table row for configuration settings table.'
category: a_hub
properties: 'a:2:{s:13:"elementStatus";a:7:{s:4:"name";s:13:"elementStatus";s:4:"desc";s:0:"";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:5:"solid";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}s:14:"elementPreview";a:7:{s:4:"name";s:14:"elementPreview";s:4:"desc";s:0:"";s:4:"type";s:9:"textfield";s:7:"options";a:0:{}s:5:"value";s:0:"";s:7:"lexicon";s:20:"romanesco:properties";s:4:"area";s:0:"";}}'

-----

<tr class="top aligned">
    <td>
        <div class="key">[[+key]]</div>
        <div class="meta"><em>[[+value:replace=`,==, `]]</em></div>
    </td>
    <td>[[+label]]</td>
    <td>[[+description]]</td>
</tr>